modLoader = 'javafml'
loaderVersion = '47'
license = 'MPL-2.0'
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = 'GregTech Modern Bugs Fix'
#logoFile = 'assets/${mod_id}/icon.png'
authors = 'Phoupraw'
description = '''格雷科技现代版漏洞修复'''
[[mixins]]
config = "${mod_id}.mixins.json"
[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
